version: "3.3"

services:

  angular:
    container_name: angular
    build: ../angular
    restart: unless-stopped
    volumes:
      - "${STORAGE_PATH}:/var/project"
    command: tail -f /dev/null
    ports:
      - 5000:5000
    networks:
      - dev_ng

  nginx:
    container_name: ng_nginx
    build: ../nginx
    restart: unless-stopped
    ports:
      - 81:81
      - 445:445
    depends_on:
      - angular
    volumes:
      - "${STORAGE_PATH}:/var/project"
      - "${LOG_PATH}:/var/log/nginx"
      - ../nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dev_ng

networks:
  dev_ng: